import {describe,it,expect,vi} from 'vitest';
import {validateImageBytes,imageMetadata,inlineDescriptor,readOutput,validateOutputUrl,MAX_OUTPUT_BYTES} from '../output';
const png=()=>Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAMAAAACCAIAAAASFvFNAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAAEklEQVR4nGP4z8AAQVDqPwMDAEHSBfsl0XwmAAAAAElFTkSuQmCC','base64');
describe('bounded untrusted output',()=>{
 it('rejects truncated PNG and malformed JPEG/WebP before committing an asset',async()=>{await expect(validateImageBytes(png().subarray(0,24))).rejects.toThrow();await expect(validateImageBytes(Buffer.from([255,216,255,192,0,8,8,0,2,0,3,0]))).rejects.toThrow();const b=Buffer.alloc(30);b.write('RIFF');b.write('WEBP',8);b.write('VP8X',12);await expect(validateImageBytes(b)).rejects.toThrow();expect(await validateImageBytes(png())).toEqual({width:3,height:2,mimeType:'image/png'});});
 it('actual bytes own MIME/dimensions; inline survives request loss',()=>{expect(imageMetadata(png())).toEqual({width:3,height:2,mimeType:'image/png'});expect(inlineDescriptor(png().toString('base64'),'image/png')).toContain('data:image/png;base64,');expect(()=>inlineDescriptor(png().toString('base64'),'image/jpeg')).toThrow();expect(()=>imageMetadata(Buffer.from('not image'))).toThrow();});
 it.each(['http://replicate.delivery/a','https://localhost/a','https://127.0.0.1/a','https://replicate.delivery.attacker.test/a','https://user:pass@fal.media/a','https://fal.media:444/a','https://169.254.169.254/a'])('rejects unsafe URL %s',url=>expect(()=>validateOutputUrl(url)).toThrow());
 it('validates every redirect before a second request',async()=>{const fetcher=vi.fn(async()=>new Response(null,{status:302,headers:{location:'http://169.254.169.254/latest'}}));await expect(readOutput('https://fal.media/image',AbortSignal.timeout(1000),fetcher)).rejects.toThrow();expect(fetcher).toHaveBeenCalledTimes(1);});
 it('rejects oversized headers and streams',async()=>{await expect(readOutput('https://fal.media/image',AbortSignal.timeout(1000),vi.fn(async()=>new Response('a',{headers:{'content-length':String(MAX_OUTPUT_BYTES+1)}})))).rejects.toThrow('too large');await expect(readOutput('https://fal.media/image',AbortSignal.timeout(1000),vi.fn(async()=>new Response(Buffer.alloc(MAX_OUTPUT_BYTES+1))))).rejects.toThrow('too large');});
 it('allows a bounded provider redirect and verifies actual media',async()=>{const fetcher=vi.fn().mockResolvedValueOnce(new Response(null,{status:302,headers:{location:'https://v3.fal.media/result'}})).mockResolvedValueOnce(new Response(png()));expect(await readOutput('https://fal.media/image',AbortSignal.timeout(1000),fetcher)).toEqual(png());expect(fetcher).toHaveBeenCalledTimes(2);});
});
