"use client";
import {useFocusTrap} from '@/hooks/use-focus-trap';
import type {WorkspaceDraft} from '@/lib/workspace/contracts';
export function SourcePreviewDialog({value,current,onCancel,onConfirm,busy=false,returning=false,currentRecipe,currentVariables,currentBinding}:{value:unknown;current:WorkspaceDraft|null;onCancel:()=>void;onConfirm:()=>void;busy?:boolean;returning?:boolean;currentRecipe?:unknown;currentVariables?:unknown;currentBinding?:string}) {
 const {containerRef}=useFocusTrap({active:true,onEscape:onCancel});
 const source=(value??{}) as Record<string,unknown>;
 const fields=[['Prompt',current?.customPrompt,source.promptSnapshot],['Negative prompt',current?.negativePromptText,source.negativePromptSnapshot],['Parameters',current?.params,source.params],['Control and variable values',current?.control,source.promptControlSnapshot],['Recipe',currentRecipe,source.recipe],['Variables',currentVariables,source.variables],['Model binding',currentBinding,source.modelName?{provider:source.provider??'Not recorded',model:source.modelName}:source.binding]];
 const show=(v:unknown)=>v===null||v===undefined?'Not available':typeof v==='string'?v:JSON.stringify(v,null,2);
 return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-[var(--surface-page)]/80 p-4"><section ref={containerRef} tabIndex={-1} role="dialog" aria-modal="true" aria-label="Preview direction change" className="max-h-[85dvh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-[var(--surface-floating)] p-4 text-sm text-[var(--text-primary)] ring-1 ring-[var(--border-static)]"><h2 className="font-semibold">Review before continuing</h2><p className="mt-2">Your current direction, unsent message and tasks are preserved. {returning?"Confirm saves current edits before returning to the existing direction.":"Confirm saves current edits before creating a new draft."} Cancel makes no changes.</p>{Boolean(source.id)&&<p className="mt-2 break-all">{returning?"Source direction":"Source result"}: {String(source.id)}</p>}<div className="mt-3 space-y-3">{fields.map(([name,before,after])=><details key={String(name)} open={name==='Prompt'||name==='Parameters'} className="rounded-lg bg-[var(--surface-low)] p-3"><summary>{String(name)}</summary><div className="mt-2 grid gap-3 sm:grid-cols-2"><div><p className="text-xs text-[var(--text-muted)]">Current draft</p><pre className="whitespace-pre-wrap break-words text-xs">{show(before)}</pre></div><div><p className="text-xs text-[var(--text-muted)]">Source snapshot</p><pre className="whitespace-pre-wrap break-words text-xs">{show(after)}</pre></div></div></details>)}</div><p className="mt-3 text-xs">Unavailable historical parameters require an explicit choice before generation. History is unchanged.</p><div className="mt-4 flex justify-end gap-2"><button type="button" disabled={busy} className="btn-secondary rounded-lg px-3 py-2" onClick={onCancel}>Cancel</button><button type="button" disabled={busy} className="btn-primary rounded-lg px-3 py-2" onClick={onConfirm}>Confirm</button></div></section></div>;
}
