import { test, expect } from '@playwright/test';
import fixture from './fixtures/api-responses/analysis-v2-completed.json';
import type {WorkspaceDraft} from '../src/lib/workspace/contracts';
import { mockAuthSession, mockAgentConversation } from './helpers/mock-api';

test('AC-05 Edit only changes the proposal copy; Apply, Discard and Undo never generate', async ({page}) => {
 await mockAuthSession(page);
 const state=await mockAgentConversation(page,{replies:[{responseKind:'proposal',replyText:'Change the whole prompt.',proposalState:'pending',changes:[{target:'customPrompt',key:'',action:'set',before:null,after:'A quiet studio'}]}]});
 let renders=0;page.on('request',r=>{if(new URL(r.url()).pathname==='/api/generation'&&r.method()==='POST')renders++;});
 await page.goto('/workspace?directionId=conversation-direction');await page.getByRole('textbox',{name:'Message your creative goal'}).fill('Change the scene');await page.getByRole('button',{name:'Send',exact:true}).click();
 await page.getByRole('button',{name:'Edit draft',exact:true}).click();await page.getByRole('textbox',{name:'Proposed customPrompt'}).fill('A bright studio');expect(state.direction.draft.customPrompt).toBeNull();
 await page.getByRole('button',{name:'Apply proposal',exact:true}).click();await expect(page.getByRole('log')).toContainText('Applied at revision 1');expect(state.direction.draft.customPrompt).toBe('A bright studio');
 await page.getByRole('button',{name:'Undo changes',exact:true}).click();await expect.poll(()=>state.direction.draft.customPrompt).toBeNull();expect(renders).toBe(0);
});

const proposed={responseKind:'proposal',replyText:'Change the whole prompt.',proposalState:'pending',changes:[{target:'customPrompt',key:'',action:'set',before:null,after:'A quiet studio'}]};
async function propose(page:import('@playwright/test').Page){await page.goto('/workspace?directionId=conversation-direction');await page.getByRole('textbox',{name:'Message your creative goal'}).fill('Change the scene');await page.getByRole('button',{name:'Send',exact:true}).click();await expect(page.getByRole('button',{name:'Apply proposal'})).toBeVisible();}

test('AC-05 discard closes the proposal with zero draft or generation changes',async({page})=>{
 await mockAuthSession(page);const state=await mockAgentConversation(page,{replies:[proposed]});await propose(page);await page.getByRole('button',{name:'Discard proposal'}).click();await expect(page.getByRole('log')).toContainText('Discarded. Your draft was not changed.');expect(state.direction.draftRevision).toBe(0);expect(state.direction.draft.customPrompt).toBeNull();expect(state.commands[0].action).toBe('discard');
});
test('AC-06 stale comparison preserves latest draft and prepares an explicit typed recovery reference',async({page})=>{
 await mockAuthSession(page);const state=await mockAgentConversation(page,{replies:[proposed]});await propose(page);state.direction.draftRevision=1;state.direction.draft.customPrompt='Latest user text';state.events[0].proposalState='stale';await expect(page.getByRole('button',{name:'Request latest comparison'})).toBeVisible();await page.getByRole('button',{name:'Request latest comparison'}).click();const goal=page.getByRole('textbox',{name:'Message your creative goal'});await expect(goal).toBeFocused();await expect(goal).toHaveValue(/latest draft/);expect(state.commands).toHaveLength(0);await page.getByRole('button',{name:'Send',exact:true}).click();await expect.poll(()=>state.turns.length).toBe(2);expect(state.turns[1].references).toEqual([{kind:'event',id:state.events[0].id,analysisTaskId:null}]);expect(state.direction.draft.customPrompt).toBe('Latest user text');
});
for(const drop of [true,false])test(`AC-05 command ${drop?'unknown':'saved readback failure'} recovers by read without another command`,async({page})=>{
 await mockAuthSession(page);const state=await mockAgentConversation(page,{replies:[proposed],dropFirstCommandResponse:drop,failCommandReadbackOnce:!drop});await propose(page);await page.getByRole('button',{name:'Apply proposal'}).click();await expect(page.getByRole('button',{name:drop?'Check command status':'Refresh command result'})).toBeVisible();await page.reload();await page.getByRole('button',{name:drop?'Check command status':'Refresh command result'}).click();await expect(page.getByRole('button',{name:/Check command status|Refresh command result/})).toHaveCount(0);expect(state.commands).toHaveLength(1);expect(state.direction.draft.customPrompt).toBe('A quiet studio');
});
const structuredDraft=():WorkspaceDraft=>({control:{schemaVersion:1,trigger:'manual',intent:'same_style',detailLevel:'standard',editorMode:'text',customPromptDirty:true,enabledInvariantIds:fixture.recipe.styleInvariants.map(r=>r.id),variableValues:Object.fromEntries(fixture.recipe.contentVariables.map(v=>[v.name,v.defaultValue])),enabledModifierNames:[],modifierValues:{},adjustments:[]},customPrompt:'repeat repeat handwritten sentence.',negativePromptText:'no text',constraints:[],params:{aspectRatio:'1:1',model:'flux-2-dev',quality:'standard'},aspectRatioSource:'reference'});
test('AC-12 expert detail preview cancel is exact, accept restores derivation, evidence has typed source and focus',async({page})=>{
 await mockAuthSession(page);const state=await mockAgentConversation(page,{draft:structuredDraft(),source:{recipe:fixture.recipe,variables:fixture.recipe.contentVariables,analysisStatus:'completed'}});Object.assign(state.direction,{analysisTaskId:'analysis-real'});
 await page.goto('/workspace?directionId=conversation-direction');await page.getByRole('tab', {name:'Prompt',exact:true}).click();await page.getByTestId('detail-option-concise').click();const dialog=page.getByTestId('prompt-switch-confirm-dialog');await expect(dialog).toContainText('repeat repeat handwritten sentence.');await expect(dialog).toContainText('After');await page.getByTestId('prompt-switch-confirm-cancel').click();await expect(page.getByTestId('detail-option-concise')).toBeFocused();await page.getByRole('button',{name:'Save draft',exact:true}).click();expect(state.direction.draft.customPrompt).toBe('repeat repeat handwritten sentence.');expect(state.direction.draftRevision).toBe(0);
 await page.getByTestId('detail-option-concise').click();await page.getByTestId('prompt-switch-confirm-accept').click();await page.getByRole('button',{name:'Save draft',exact:true}).click();await expect.poll(()=>state.direction.draft.control?.detailLevel).toBe('concise');expect(state.direction.draft.customPrompt).toBeNull();
 const observation=fixture.recipe.styleProfile.lighting[0];await page.getByRole('tab', {name:'Evidence',exact:true}).click();await page.getByTestId('evidence-facet-lighting').click();await page.getByTestId(`evidence-observation-${observation.id}`).click();await page.getByRole('tab', {name:'Evidence',exact:true}).click();await expect(page.getByRole('region',{name:'Selected evidence source'})).toContainText('Analysis analysis-real');await expect(page.getByRole('region',{name:'Selected evidence source'})).toContainText('No image coordinates');await page.getByRole('button',{name:'Ask about this'}).click();const goal=page.getByRole('textbox',{name:'Message your creative goal'});await expect(goal).toBeFocused();await goal.fill('Explain this evidence');await page.getByRole('button',{name:'Send',exact:true}).click();await expect.poll(()=>state.turns.length).toBe(1);expect(state.turns[0].references).toEqual([{kind:'evidence',id:observation.id,analysisTaskId:'analysis-real'}]);
});
for(const width of [1440])test(`AC-05 proposal exact diff visual and focus ${width}`,async({page},info)=>{
 await page.setViewportSize({width,height:900});await mockAuthSession(page);await mockAgentConversation(page,{replies:[proposed]});await propose(page);await page.getByRole('button',{name:'Edit draft'}).click();const editor=page.getByRole('textbox',{name:'Proposed customPrompt'});await editor.focus();await expect(editor).toBeFocused();await expect(page.getByRole('region',{name:'Proposal changes'})).toHaveScreenshot(`proposal-${width}.png`,{animations:'disabled'});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath(`proposal-${width}.png`)});
});

test('AC-05 late analysis uses the same proposal review without exposing machine metadata',async({page})=>{
 await mockAuthSession(page);const state=await mockAgentConversation(page,{replies:[{...proposed,kind:'draft_change',inputText:'{"baseDraft":"private receipt"}',replyText:'Analysis arrived after your edit. Review before applying.'}]});await propose(page);await expect(page.getByRole('log')).not.toContainText('private receipt');await page.getByRole('button',{name:'Apply proposal'}).click();await expect(page.getByRole('log')).toContainText('Applied changes:');expect(state.direction.draft.customPrompt).toBe('A quiet studio');await page.reload();await expect(page.getByRole('log')).toContainText('A quiet studio');await expect(page.getByRole('log')).not.toContainText('pending review');
});

test('AC-12 identical manual text switches to derived mode durably and traps preview keyboard focus',async({page})=>{
 await mockAuthSession(page);const draft=structuredDraft();draft.customPrompt=null;draft.control!.editorMode='variables';draft.control!.customPromptDirty=false;
 const state=await mockAgentConversation(page,{draft,source:{recipe:fixture.recipe,variables:fixture.recipe.contentVariables,analysisStatus:'completed'}});await page.goto('/workspace?directionId=conversation-direction');await page.getByRole('tab', {name:'Prompt',exact:true}).click();await page.getByTestId('editor-mode-option-text').click();const editor=page.getByTestId('fulltext-prompt-editor');const original=await editor.inputValue();await editor.fill(original+' temporary');await editor.fill(original);await page.getByRole('button',{name:'Save draft',exact:true}).click();await expect.poll(()=>state.direction.draft.customPrompt).toBe(original);
 await page.getByTestId('editor-mode-option-variables').click();const cancel=page.getByTestId('prompt-switch-confirm-cancel'),accept=page.getByTestId('prompt-switch-confirm-accept');await expect(cancel).toBeFocused();await page.keyboard.press('Shift+Tab');await expect(accept).toBeFocused();await page.keyboard.press('Tab');await expect(cancel).toBeFocused();await page.keyboard.press('Escape');await expect(page.getByTestId('editor-mode-option-variables')).toBeFocused();expect(state.direction.draft.customPrompt).toBe(original);
 await page.getByTestId('editor-mode-option-variables').click();await accept.click();await page.getByRole('button',{name:'Save draft',exact:true}).click();await expect.poll(()=>state.direction.draft.customPrompt).toBeNull();await page.reload();await expect(page.getByTestId('editor-mode-option-variables')).toHaveAttribute('aria-pressed','true');expect(state.direction.draft.customPrompt).toBeNull();
});
