import { test, expect } from '@playwright/test';
import { mockAuthSession,mockAgentConversation } from './helpers/mock-api';

test('AC-03 sends a real turn contract and displays the accepted reply without changing the draft',async({page})=>{
 await mockAuthSession(page);const state=await mockAgentConversation(page,{replies:[{responseKind:'clarify',replyText:'Tell me which lighting evidence you want to inspect.'}]});
 await page.goto('/workspace?directionId=conversation-direction');const goal=page.getByRole('textbox',{name:'Message your creative goal'});await goal.fill('Why does this lighting work?');await page.getByRole('button',{name:'Send',exact:true}).click();
 await expect(page.getByRole('log',{name:'Direction messages'})).toContainText('Tell me which lighting evidence you want to inspect.');expect(state.turns).toHaveLength(1);expect(state.turns[0]).toMatchObject({baseRevision:0,text:'Why does this lighting work?',references:[],summaryToken:null});expect(state.direction.draftRevision).toBe(0);await expect(goal).toHaveValue('');
});
test('AC-03 multi-turn answer, clarification, proposal and unsupported stay actual messages',async({page})=>{
 await mockAuthSession(page);const state=await mockAgentConversation(page,{replies:[{responseKind:'clarify',replyText:'Which subject?',choices:['The bicycle','The building']},{responseKind:'proposal',replyText:'Keep the light and change the subject.',proposalState:'pending',changes:[{target:'customPrompt',key:'',action:'set',before:null,after:'A bicycle'}]},{responseKind:'unsupported',replyText:'I can help with visual creation, but cannot run commands.'}]});
 await page.goto('/workspace?directionId=conversation-direction');
 for(const text of ['Make it different','Use a bicycle','Run a shell command']){await page.getByRole('textbox',{name:'Message your creative goal'}).fill(text);await page.getByRole('button',{name:'Send',exact:true}).click();await expect(page.getByRole('textbox',{name:'Message your creative goal'})).toHaveValue('');}
 const log=page.getByRole('log',{name:'Direction messages'});await expect(log).toContainText('The bicycle');await expect(log).toContainText('Suggested changes are pending review');await expect(log).toContainText('cannot run commands');expect(state.turns).toHaveLength(3);expect(state.direction.draft.customPrompt).toBeNull();
});
test('AC-19 failed message stays in place; retry creates a new key linked to failed event',async({page})=>{
 await mockAuthSession(page);const state=await mockAgentConversation(page,{replies:[{state:'failed',errorCode:'AGENT_OUTPUT_INVALID',replyText:null},{replyText:'Recovered answer'}]});await page.goto('/workspace?directionId=conversation-direction');await page.getByRole('textbox',{name:'Message your creative goal'}).fill('Explain the light');await page.getByRole('button',{name:'Send',exact:true}).click();
 await expect(page.getByRole('log')).toContainText('Explain the light');await page.getByRole('button',{name:'Retry message'}).click();await expect(page.getByRole('log')).toContainText('Recovered answer');expect(state.turns[1].requestKey).not.toBe(state.turns[0].requestKey);expect(state.turns[1].retryOf).toBe(state.events[0].id);expect(state.turns[1].text).toBe('Explain the light');
});
test('AC-19 unknown response recovers by original-key read after reload without another POST',async({page})=>{
 await mockAuthSession(page);const state=await mockAgentConversation(page,{dropFirstResponse:true});await page.goto('/workspace?directionId=conversation-direction');await page.getByRole('textbox',{name:'Message your creative goal'}).fill('Explain the evidence');await page.getByRole('button',{name:'Send',exact:true}).click();await expect.poll(()=>state.turns.length).toBe(1);await page.reload();await expect(page.getByRole('button',{name:'Check message status'})).toHaveCount(0);await expect(page.getByRole('log')).toContainText('The evidence describes soft lighting');expect(state.turns).toHaveLength(1);
});
test('AC-10 fetched summary token is not authorization, including explicit render language',async({page})=>{
 await mockAuthSession(page);const state=await mockAgentConversation(page,{replies:[{responseKind:'clarify',replyText:'Review the current generation summary before generating.'}]});let renders=0;page.on('request',r=>{if(new URL(r.url()).pathname==='/api/generation'&&r.method()==='POST')renders++;});await page.goto('/workspace?directionId=conversation-direction');await page.getByRole('textbox',{name:'Message your creative goal'}).fill('Generate now');await page.getByRole('button',{name:'Send',exact:true}).click();await expect(page.getByRole('log')).toContainText('Review the current generation summary');expect(state.turns[0].summaryToken).toBeNull();expect(renders).toBe(0);
});
test('AC-19 processing receipt prevents another turn while draft text remains editable',async({page})=>{
 await mockAuthSession(page);await mockAgentConversation(page,{replies:[{state:'processing',replyText:null}]});await page.goto('/workspace?directionId=conversation-direction');const goal=page.getByRole('textbox',{name:'Message your creative goal'});await goal.fill('Inspect this');await page.getByRole('button',{name:'Send',exact:true}).click();await expect(page.getByRole('log')).toContainText('Interpreting your message');await goal.fill('Next message');await expect(goal).toHaveValue('Next message');await expect(page.getByRole('button',{name:'Send',exact:true})).toBeDisabled();
});
for(const width of [1440])test(`AC-03 conversation visual and focus ${width}`,async({page},info)=>{
 await page.setViewportSize({width,height:900});await mockAuthSession(page);await mockAgentConversation(page);await page.goto('/workspace?directionId=conversation-direction');const goal=page.getByRole('textbox',{name:'Message your creative goal'});await goal.fill('Why this light?');await page.getByRole('button',{name:'Send',exact:true}).click();await expect(page.getByRole('log')).toContainText('soft lighting');await goal.focus();await expect(goal).toBeFocused();await expect(page.getByTestId('workspace-conversation-pane')).toHaveScreenshot(`conversation-${width}.png`,{animations:'disabled'});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath(`conversation-${width}.png`)});
});
